# .github/workflows/ci_cd.yaml

  name: CI Pipeline

  on:
    push:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@6
        with:
          python-version: 3.13
      - uses: iterative/setup-cml@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main file
        run: |
          python main.py

      - name: Run Tests
        run: |
         python -m unittest discover

      - name: Create CML report
        env:
           REPO_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |

          echo "# First Line of our report" >> report.md
          echo "## Bar Plots" >> report.md
          echo '![](./bars.png "Bar Plot")' >> report.md
          echo "## Line Plots" >> report.md
          echo '![](./line.png "Line Plot")' >> report.md
      
